indexstyle.css

Added custom scroll bar

---

index.html
length.html

Closes #13 
This calculator converts measurement between any of the following units: Feet, Meters,Inches,Centimeters,Yards,Kilometers,Miles.

Length Calculator

---

bitwise.html
index.html

Closes #15 
This calculator takes two decimal numbers as input and can interpret the bitwise AND, bitwise OR and bitwise XOR.

Bitwise calculator

---

caesarcipher.html
index.html

Closes #19 
The Caesar Cipher technique is one of the earliest and simplest method of encryption technique. It’s simply a type of substitution cipher, i.e., each letter of a given text is replaced by a letter some fixed number of positions (offset) down the alphabet.

Caesar cipher calculator

---

README.md

closes #30 
Contribution Section
Github Badges

Added contributions section and badges in readme

---

script.js
style.css

I have improved the factorial logic to not give infinity it will give the factorial of large numbers i have shown one demo with this PR and kindly add the jwoc label before merging.

Factorial logic change

---

CONTRIBUTING.md
LICENSE

Added CONTRIBUTING.md and LICENSE

---

bmi.html
script.js
style.css

 Fixed bmi chart

---

hcf.html
hcflcm.html
index.html
script.js
style.css

Hcf Calculator included

---

script.js

present date issue's solved in age calculator

---

index.html
romanint.html
script.js
style.css

Roman Numeral To Integer Calculator 

---

index.html
sip.html
style.css

This takes the monthly investment amount, growth rate and time period of investment then tells the total value of investment(growth+original)

added a new calculator for calculating SIP future value

---

alg-deriv.html
index.html
script.js
style.css

Added an algebraic derivative calculator
Features:
- A short description of an algebraic expression
- Calculate derivative of a user-given algebraic term
- Check for empty input and send alert if empty input is given
Closes #51 
Note: I meant an algebraic derivative calculator and not a polynomial derivative calculator. I mixed up the mathematical terms in issue name. I'm sorry for the confusion.
Video link: https://imgur.com/a/iBoGZNw

Algebraic Derivative Calculator - #51

---

Days-Calculator.html
age.html
alg-deriv.html
bindec.html
bitwise.html
bmi.html
caesarcipher.html
calculator.html
currencyConverter/ccstyle.css
currencyConverter/currencyConverter.html
equation.html
factorial.html
hcflcm.html
length.html
logarithm.html
power.html
romanint.html
sip.html
style.css
temperature.html

All changes have been done positively. 
Attached all the names inside each calc. 
Updated all  mismatched font style. 
**kindly review this pr and advise if any changes are required**

[Fixed] #59 attached calculators name inside and [FIXED] #60 Updated fonts

---

binomialCoefficient.html
index.html
theme.css

Closes #78 
The Binomial Coefficient Calculator is used to calculate the binomial coefficient C(n, k) of two given natural numbers n and k .

Binomial coefficient

---

style.css

Overscrolling of page is solved

---

Days-Calculator.html
age.html
bindec.html
bitwise.html
bmi.html
caesarcipher.html
calculator.html
currencyConverter/ccstyle.css
currencyConverter/currencyConverter.html
equation.html
factorial.html
hcflcm.html
length.html
logarithm.html
power.html
romanint.html
script.js
sip.html
style.css

Copy To Clipboard Feature has been added. Please Merge it.

Copy to clipboard

---

index.html

Line 33 and 312  was "Index.html" Changed It To "#hero".Since ,It Works Faster{Hash Page Linking} And Retains Animation Of Page Flow
Some Textual Changes In Design

Update index.html    .... Issue #95

---

data-calc.html
index.html

Added Data Converter Calculator that interconverts B, KB, MB, GB, TB into each other
Closes #90

Added Data Converter Calculator #9

---

Days-Calculator.html
age.html
alg-deriv.html
bindec.html
binomialCoefficient.html
bitwise.html
bmi.html
caesarcipher.html
calculator.html
currencyConverter/currencyConverter.html
equation.html
factorial.html
hcflcm.html
length.html
logarithm.html
power.html
romanint.html
sip.html
style.css
temperature.html

Screenshot :
resolves issue #96

Added home icon

---

landing.css

#108 issue resolved Added media query to align the size of SVG according to screen size

#108 issue resolved : Make landing page responsive

---

index.html

Hey, I have resolved issue #115 under JWOC. Kindly review @Srijita-Mandal

Footer links in same Tab

---

alg-deriv.html
currencyConverter/currencyConverter.html
index.html
script.js

Changed The Default Of Calculator From "1" To Null Of "Algebraic Derivative Calculator" & "Currency Converter"

Closes Issue #95 --"Currency Converter Bug"

---

Image/Chevron.svg
index.html
indexstyle.css
script.js

`Image/Chevron.svg`, `index.html`, `indexstyle.css`, `script.js`

Add: ScrollToTop Button

---

index.html
weight-calc.html

Add weight converter with units kg, g, lb, and ton. It is also responsive, dark mode enabled and has reset button. #113

Add weight converter

---

alg-deriv.html
currencyConverter/currencyConverter.html
index.html
script.js

Reverts Srijita-Mandal/fix-your-nums#118

Revert "Closes Issue #95 --"Currency Converter Bug""

---

index.html
script.js
style.css
trig-calc.html

Added a trigonometric calculator
Features:
- user inputs an angle in degree or radian
- calculate sin, cos, tan, sec, cosec and cot of the given angle
- user has the ability to choose which trig functions to be calculated (from a checklist)
- appropriate form validations for empty or invalid input
- RESET button to clear previous inputs
- Dark theme
Closes #84 
I'm unable to add submit using Enter key feature.
Link: https://imgur.com/58jxjH0

Trigonometric Calculator - #84

---

style.css

closes #112 
Fixed the overflow in y-axis in all pages.

Fixed overflow in y-axis

---

data-calc.html
script.js
style.css

#121 
@Srijita-Mandal please merge my pr. The output for the above issue can be shown here

data converter becomes responsive and dark mode is also enabled

---

sip.html
theme.css

Closes #123 
Fixed the ui issue of sip calculator

Fix SIP UI

---

data-calc.html
script.js
style.css
weight-calc.html

improved weight converter

---

Days-Calculator.html
age.html
alg-deriv.html
base.html
binomialCoefficient.html
bitwise.html
bmi.html
calculator.html
currencyConverter/ccstyle.css
currencyConverter/currencyConverter.html
data-calc.html
equation.html
factorial.html
hcflcm.html
length.html
logarithm.html
power.html
result.css
romanint.html
script.js
sip.html
temperature.html
trig-calc.html
weight-calc.html

I changed the UI for the result section

changed result section ui

---

script.js
trig-calc.html

improved trigonometric calculator

---

go_to_top.css
go_to_top.js
index.html

Live site link:
https://swadhin2001.github.io/fix-your-nums/

Back to Top Button Added

---

caesarcipher.html
caesardark.css
sip.html

Closes #150 
Fixes dark mode in Caesar Cipher Calculator and SIP calculator

Dark mode fix

---

currencyConverter/ccstyle.css
currencyConverter/cctheme.js
currencyConverter/currencyConverter.html

Resolved the previous conflict issue.

modified CC dark-mode

---

romanint.html

The button now shows the word Convert in both light and dark mode

Fixed the bug in Roman Numeral Convert Button

---

index.html
sleep.html
sleepdark.css

Closes #168 
The provided Sleep Calculator calculates your bed time based on the time at which you want to wake up. It ensures that you get proper sleep in 90 mins cycles.

Sleep calculator

---

bitwise.html
style.css

-Changed the user interface to a drop down list from the button layout to fit better with the other calculators which have many options.
-Added 6 more bitwise operators.
- Fixed a bug regarding the reset button needing 2 taps to work.
-Now the output field only appears when a output is present.
-Also added the option to press enter to press the submit button.
I feel that this was complex work, so I would be really grateful if you raised the difficulty of the issue provided you think its justified.

Added NOT, NAND, NOR, XNOR, Shift Right, Shift Left operation to Bitwise Calculator

---

currencyConverter/ctheme.css
currencyConverter/currencyConverter.html

I updated the UI of the dark mode

updated the dark mode UI

---

index.html
nthRoot.html
script.js

Screenshots :
resolves issue #175

Added nth root calculator

---

sleep.html

This is with reference to #174 .Fixes reset button in sleep calculator

fix reset button sleep calculator

---

binomialCoefficient.html
currencyConverter/ctheme.css
currencyConverter/currencyConverter.html
pnc.html
script.js
theme.css

I have updated the permutation and combination calculator page and also add a border on home icon

updated permutation and combination calculator page

---

index.html
sales-tax.html
script.js

Sales Tax Calculator #139, Solved

---

index.html
speed-calc.html

Screenshots:
resolves issue #185

Added Speed convertor

---

index.html
indexstyle.css

changed hero section

---

logarithm.html
script.js

Added a special case for handling the constant e in both base and argument.
Closes #197

Added the option to get log for any valid base in Logarithm calculator

---

cubicEquationRoots.html
index.html
result.css
style.css

[Cubic Equation Roots.webm](https://user-images.githubusercontent.com/107767172/221751663-2af845c9-09d9-4556-a6d3-c782db9ce16f.webm)

Cubic equation roots calculator added

---

index.html
indexstyle.css

Updated the nav bar .
added  icons to look good .
updated the paragrapg fonts in landing page.

Fixed issue #138

---

Days-Calculator.html
age.html
base.html
bitwise.html
bmi.html
calculator.html
data-calc.html
emi.html
equation.html
factorial.html
hcflcm.html
logarithm.html
nthRoot.html
num-to-word.html
pnc.html
power.html
romanint.html
sales-tax.html
sip.html
speed-calc.html
temperature.html
trig-calc.html
weight-calc.html

overscrolling of particular calc is solved

---

catalan.html
catalanDark.css
index.html

Closes #213 
The Catalan numbers are a sequence of positive integers that appear in many counting problems in combinatorics.
They count certain types of lattice paths, permutations, binary trees, and many other combinatorial objects.

Catalan number

---

index.html
volume_calculator.html

Screenshots:
resolves issue #208

Added Volume Calculator

---

index.html
retirement.html

I have updated please check it

Retirement calculator updated

---

Interest.html
index.html
interest.js

Interest Calculator Added

---

complexDark.css
complexNumber.html
index.html

Closes #216 
This calculator does basic arithmetic on complex numbers.

Complex number

---

energy_calc.html
index.html

Screenshots:
resolves issue #229

Added energy converter

---

ProfitLoss/index.html
ProfitLoss/main.js
ProfitLoss/style.css

profitLoss calculator

---

index.html

Profit and loss calculator is added to homepage

Profit loss calculator

---

testimonial.css
testimonial.html

Hey @Srijita-Mandal , I have resolved issue #232 under JWOC. Kindly review
https://user-images.githubusercontent.com/91181981/222903665-f0ddc00d-03d0-4f86-a77f-d4962779983d.mp4

Testimonial UI

---

divisor.html
divisorDark.css
index.html

Closes #227 
Divisor Calculator will be used calculate divisors of a number, number of divisors and their sum.

Divisor calculator

---

energy_calc.html
index.html
timeCalc.html

Screenshots:
resolves issue #243

Added time calculator

---

alg-deriv.html
script.js

With this enhancement, the `Algebraic-derivative Calculator` will find differentiation of a polynomial function f(x) with respect to x.
[demo13.webm](https://user-images.githubusercontent.com/90945182/222953922-3151aaf9-8f52-422a-ae39-de723c6db250.webm)

[Enhancement] Added functionality to find d/dx (f(x)

---

testimonial.html

Resolves issue #250. Have added favicon on testimonial page

Issue #250

---

script.js
sip.html

#233 
The output of the above issue is shown below:

added reset button in SIP

---

aboutus.css
aboutus.html
index.html
testimonial.html

modify navbar

---

index.html
indexstyle.css

Implemented a responsive Search Bar.

Added Search Bar

---

testimonial.html

Integrated Footer in Site  Closes #Issue 248

---

testimonial.css

Resolves #265 under JWOC. @Srijita-Mandal kindly review
https://user-images.githubusercontent.com/91181981/223178700-6204d7e2-a0ae-4f5e-a853-5828692a451e.mp4

Testimonial Responsiveness

---

retirement.html
script.js

added reset button in retirement calc and also fixed Ui

---

index.html
powerCalc.html
volume_calculator.html

Screenshots :
resolves issue #267

Added Power Convertor

---

MMM-calculator.html
MMM-calculator.js
index.html

Mean Median Mode Calculator

---

index.html
standardDev.html

[demo22.webm](https://user-images.githubusercontent.com/90945182/223436095-e248268f-42ae-4e7a-97ba-88f5d611073c.webm)

[Feature] Added Standard Deviation Calculator

---

index.html
pressureCalc.html

Screenshots :
resolves issue #279

Added pressure calculator

---

aboutus.css
aboutus.html

Screenshots :
https://user-images.githubusercontent.com/95460021/223715685-9b85f55a-2cd6-4ce1-9d12-4900f92ec88a.mp4
Resolves issue #288

Updated the about us section

---

indexstyle.css

cards color changed

---

Horsepower.html
index.html

Horsepower Calculator Added

---

html_files/aboutus.html
html_files/testimonial.html

Closes #290
Reference pr #295
https://s-ishita.github.io/fix-your-nums/

Scroll button Fix

---

html_files/testimonial.html

fix footer icons

---

html_files/aboutus.html

Closes #303 
https://user-images.githubusercontent.com/104543751/224003565-99cf92a7-ae4a-48fa-80b3-72f0c93d3ad3.mp4

fix footer links

---

css_files/style.css
html_files/pythagorasTheorem.html
index.html

[demo29.webm](https://user-images.githubusercontent.com/90945182/224058676-f51c3d40-552f-4110-a83c-e633bd57bc19.webm)

297 patch pythagoras

---

html_files/slope.html
index.html

Slope Calculator

---

html_files/areacalc.html
index.html

Screenshots :
resolves issue #304

Added area calculator

---

html_files/bmi.html
html_files/caesarcipher.html
js_files/script.js

added reset button in caesar cypher and improved UI

---

html_files/energy_calc.html

fixed all bugs in energy calculator

---

html_files/alg-deriv.html
html_files/alg-integral.html
html_files/complexArgMod.html
html_files/complexNumber.html
html_files/standardDev.html
index.html

Reset buttons added and bug fixed #319

---

html_files/random.html
index.html

Random number generator

---

html_files/css_units.html
index.html

added css unit measurement converter

---

html_files/vat.html
index.html

Closes #343 
Calculates the Value Added Tax (VAT) on products or services.

VAT calculator

---

html_files/calculator.html
js_files/script.js

A user might need to consecutively add or multiply or do anything with the number he/she entered continuously without entering new values. 
I've added a button by which he/she can easily carry out same operation multiple times.
[demo35.webm](https://user-images.githubusercontent.com/90945182/224378440-58b69561-9ba4-4d20-8593-ba39f1ecfe87.webm)

[Feature] Added Recalculating Button

---

html_files/week.html
index.html

Week calculator

---

js_files/script.js

improved the output we get after reset button

---

js_files/script.js

fixed all bugs in console

---

html_files/matrix.html
index.html

Calculates adjoint of matrix
Closes #355

Adjoint Calculator

---

indexstyle.css

color changes are done 

---

html_files/densityUnit.html
index.html

Interconverts kg/l, kg/m^3, g/L, g/mL and oz/gal

added density unit calculator

---

html_files/speed.html
index.html

Speed calculator

---

html_files/accelaration.html
index.html

Accelaration calculator

---

html_files/profitloss.html
html_files/sales-tax.html
js_files/main.js

improved reset button in both Profit/Loss and Sales Tax calculator

---

contributors.json
css_files/aboutus.css
css_files/contributors.css
html_files/aboutus.html
js_files/contributors.js

Created a JSON file that stores the contributor's data.
Use JS for fetching Data from JSON file and display it to HTML sec.
Made a responsive and attractive card layout for displaying contributor's details.
https://user-images.githubusercontent.com/76838565/224533497-c7aae785-91b3-4323-ac36-3640db1181fc.mp4

Added Our Team

---

html_files/distance.html
index.html
js_files/distance.js

Distance Calculator Added

---

css_files/translate.css
html_files/aboutus.html
html_files/contact.html
html_files/testimonial.html
index.html
indexstyle.css
js_files/translate.js

Hey @Srijita-Mandal, I have resolved issue #383 under JWOC. Kindly review
https://user-images.githubusercontent.com/91181981/224549314-47c64f67-530c-4d08-8faa-e4e2cb0bb4a9.mp4

Language Translator

---

html_files/contact.html

[Feature] Added Form Submit Endpoint

---

css_files/style.css
html_files/tipCalc.html
index.html
js_files/tipCalc.js

Tip Calculator and changed $ symbol to Rs in output section

---

css_files/style.css
html_files/tipCalc.html
index.html
js_files/tipCalc.js

added TIP Calculator to the website

---

html_files/pressure.html
index.html

Pressure Calculator

---

html_files/cryptocalc.html
index.html
js_files/cryptolist.js

added the cryptocalculator as stated.
after reset:

added the cryptocalculator code

---

html_files/surface-area.html
index.html
js_files/surface-area.js

Added Surface Area Calculator

---

css_files/style.css
html_files/aboutus.html
html_files/bloodsugar.html
index.html
js_files/bslreading.js

adding the blood sugar level calculator as per the issue.

adding the blood sugar level calculator

---

contributors.json
html_files/intensity_convertor.html
index.html

Screenshots:
resolves issue #396

Added intensity units converter

---

css_files/budget.css
html_files/budget.html
index.html
js_files/budget.js

Closes #404 
Also , please increase the difficulty level...
https://user-images.githubusercontent.com/104543751/224634731-9fb08793-dfab-476d-a643-db2ef234a8f4.mp4

Budget calculator

---

html_files/work.html
index.html

Work calculator

---

html_files/volumecalc.html

Screenshots:
resolves issue #416

Improved Volume Calculator

---

html_files/kinetic.html
index.html

Kinetic energy calculator

---

css_files/contact.css
html_files/contact.html

Footer updated in contact us

---

html_files/graph.html
index.html

graphing calc added

---

html_files/potential_energy.html
index.html

Screenshots:
resolves issue #423

Added potential energy calculator

---

html_files/Sum-of-Series.html
index.html

Sum of Series Calculator Added

---

css_files/ProfitMargin.css
html_files/ProfitMargin.html
index.html
js_files/ProfitMargin.js

Profit margin calculator added

---

.vscode/settings.json
css_files/style.css
html_files/aboutus.html
html_files/amgmhm.html
index.html
js_files/amgmhm.js

the results are below:
a. harmonic mean
b.geometric mean
c.arithmetic mean

Adding the Mean converting calculator

---

html_files/arithmetic_prog.html
index.html

- The user will enter the nth tern of the series
- First data will be provided
- Subsequently the series will be generated w.r.t given nth term

Added AP generator

---

css_files/aboutus.css
html_files/aboutus.html

About list updated

---

html_files/force.html
index.html

Force calculator

---

html_files/Power-calculation.html
index.html

Added Power-Calculations  Calculator

---

html_files/gravitationalForce.html
index.html

Screenshots:
resolves issue #439

Added gravitational force calculator

---

html_files/kinetic.html
html_files/matrix.html
html_files/potential_energy.html
html_files/work.html

Fixed the responsiveness for work calculator, matrix adjoint calculator, Kinetic energy, and potential energy calculator.

Fixed Responsiveness

---

html_files/heron.html
index.html

- The user will enter three sides of Triangle
- Subsequently the Area will be calculated using **Heron's Formula**
[herons.webm](https://user-images.githubusercontent.com/90945182/225041501-788e9791-6464-482e-b316-261f78ec4a34.webm)

Added Heron's Calculator

---

html_files/Heat.html
index.html

Added Heat Calculator

---

html_files/variance.html

Resolves issue #454 . @Srijita-Mandal kindly review
https://user-images.githubusercontent.com/91181981/225053912-df7ec13d-0060-442c-b8f7-f639ad0244b4.mp4

Variance Calculator

---

html_files/discount.html
index.html

Closes #433 
https://user-images.githubusercontent.com/104543751/225060827-cb024d28-b0b5-4bbe-aa01-11c0604c4bc7.mp4

Discount calculator

---

html_files/Sum-of-n fibonacci-nth fibonaci.html
index.html
js_files/Sum-of-N fibonacci.js

Added Sum of N Fibonacci Number and Nth Fibonacci Calculator

---

html_files/invoice.html
index.html

Invoice calculator

---

html_files/range.html
index.html

Hey @Srijita-Mandal , I have resolved issue #472 under JWOC. Kindly review

Range Calculator

---

html_files/resistance.html
index.html

https://saishreekouda.github.io/fix-your-nums/

Resistance calculator added

---

css_files/aboutus.css
css_files/team.css
html_files/contact.html
html_files/team.html
html_files/testimonial.html
index.html

resolves #458 
added the link of same in the footer of all pages.
https://khushimarothi.github.io/fix-your-nums/html_files/team.html

Team page created

---

html_files/mechanical
index.html

Resolves issue #478. @Srijita-Mandal kindly review

Mechanical Energy

---

html_files/Electricitybill.html
index.html

Electricity Bill Calculator Added

---

html_files/armstrongNumber.html
index.html

Screenshots:
resolves issue #471

Added Armstrong number Checker

---

html_files/voltage.html
index.html

https://saishreekouda.github.io/fix-your-nums/html_files/voltage.html

voltage calculator added

---

html_files/aspectRatio.html
index.html

Aspect ratio

---

html_files/palindromeNumberChecker.html
index.html

Screenshots:
resolves issue #496

Added palindrome number checker

---

css_files/Fraction.css
html_files/Fraction.html
index.html
js_files/Fraction.js

Added Fraction Calculator

---

html_files/Power-of-lens.html
index.html

Added Power of Lens Calculator

---

css_files/gst.css
html_files/gst.html
index.html
js_files/gst.js

Added GST Calc

---

html_files/friction.html
index.html

Friction Calculator

---

html_files/capacitance.html
index.html

Added capacitance calculator

---

css_files/aboutus.css
html_files/aboutus.html

Closes #515 
https://user-images.githubusercontent.com/104543751/225358769-50dd5b59-2afe-4b25-9a7a-ef944952ad4b.mp4

Counter Animation added

---

html_files/shearstress.html

Resolves issue #508 
@Srijita-Mandal kindly review

Shear Stress Calculator

---

html_files/primeNumberChecker.html
index.html

Screenshots :
resolves issue #511

Added prime number checker

---

html_files/ForceCalculator.html

Proper Units are added in placeholder of  force calculator

---

html_files/sparse.html
index.html

Would be glad if you'd merge this PR @Srijita-Mandal

Added Sparse to Compact Matrix Calculator

---

html_files/viscosity.html
index.html

https://saishreekouda.github.io/fix-your-nums/html_files/viscosity.html

Viscosity calculator

---

js_files/script.js

@Srijita-Mandal  Updated the modulo calculator. Issue no #459.

updated Modulo calculator

---

html_files/Sum of n numbers.html
index.html
js_files/Sum of n numbers.js

Added sum of n numbers

---

html_files/frequency.html
index.html

Added frequency Calculator

---

html_files/stress.html
index.html

Stress Calculator

---

html_files/electricalenergy.html
index.html

Resolves issue #524 
@Srijita-Mandal kindly review

Electrical Energy Calculator

---

.vscode/settings.json
css_files/aboutus.css
html_files/aboutus.html

Icons added

---

html_files/cube.html
index.html

Added Perfect Cube Generator

---

html_files/vector.html

Merge this after Review @Srijita-Mandal

Fixed broken CSS of the Calculator

---

html_files/KaprekarNumber.html
index.html

Screenshots:
resolves issue #523

Added kaprekar number checker

---

css_files/testimonial.css

@Srijita-Mandal check and merge...........colour change and hover effects added

ui enhancement of testmonial page

---

css_files/investment.css
html_files/investment.html
index.html
js_files/investment.js

Added Investment Calculator which basically calculates the return on investment in percentage.

Added Investment Calculator

---

html_files/mass.html
index.html

Mass calculator

---

html_files/revenue.html
index.html

Hey @Srijita-Mandal , I have resolved issue #547 under JWOC. Kindly review

Total Revenue Generator Calculator

---

html_files/momentum.html
index.html

Hey @Srijita-Mandal , i've resolved issue #561 under JWOC. Kindly review

Momentum Calculator

---

html_files/lca.html
index.html

Added LCA calculator

---

.vscode/settings.json
css_files/aboutus.css
html_files/aboutus.html

added complete list of calculators
Closes: #562 @Srijita-Mandal

updated about page

---

html_files/wavelength.html
index.html

Wavelength calculator

---

html_files/impulse.html
index.html

Impulse calculator

---

html_files/molarity.html
index.html

Molarity Calculator

---

html_files/molality.html
index.html

Molality Calculator 

---

html_files/amicableNumberChecker.html
index.html

Screenshots:
resolves issue #553

Added amicable number checker

---

html_files/timezone.html
index.html

Added Timezone

---

html_files/time.html
index.html

Time period Calculator

---

css_files/FDT.css
html_files/FDT.html
index.html
js_files/FDT.js

Added Frequency Distribution Table

---

html_files/happyNumberChecker.html
index.html

Screenshots :
resolves issue #597

Added happy number checker

---

html_files/massp.html
index.html

Mass percentage calculator

---

html_files/BodyFatPercentage.html
index.html

Closes: #599  @S-ishita 
This time did according to you!

Added BODY FAT Percentage calculator

---

html_files/volp.html
index.html

Volume percentage Calculator

---

html_files/perfectNumberChecker.html
index.html

Screenshots :
resolves issue #613

Added Perfect Number checker

---

html_files/luckyNumberChecker.html
index.html

Screenshots :
resolves issue #621

Added Lucky Number Checker

---

html_files/massvolp.html
index.html

Mass by volume percentage calculator

---

html_files/torque.html

References pr #600 
https://user-images.githubusercontent.com/91181981/225716410-81fb76e3-4ee6-49fe-b8f2-c2c16a5072fd.mp4

Torque Responsivenss

---

html_files/zscore.html
index.html

Addded Z-Score Calculator
